global:
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 15s
runtime:
  gogc: 75
scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: [ 'localhost:9090' ]
  #- job_name: 'tempo'
  #  static_configs:
  #    - targets: [ 'tempo:3200' ]
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8889' ]